Repository weareprestatech/hotpdf, pull requests merged in 2024-01, with the labels that each got.

#1 Enabling CI pipelines on pull requests to main
  .github/workflows/pull-requests-ci.yml
  README.md
  generate_release_notes.py
  requirements.txt
  setup.py
Labels: enhancement

#8 Reduce complexity of load_memory_map function and flake8 max_complexity
  .github/workflows/pull-requests-ci.yml
  hotpdf/memory_map.py
Labels: enhancement

#10 build: CI/CD quality of life improvements
  .github/workflows/pull-requests-ci.yml
  .github/workflows/python-publish.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  Py39Pipfile
  mypy.ini
  requirements.txt
  ruff.toml
  setup.py
Labels: CI/CD

#18 Update test.yml
  .github/workflows/test.yml
Labels: CI/CD

#21 Update python-publish.yml
  .github/workflows/python-publish.yml
Labels: CI/CD

#26 build: deployment
  pyproject.toml
Labels: CI/CD

#33 build: add mypy to pre-commit
  .pre-commit-config.yaml
  docs/source/generated/hotpdf.data.classes.ElementDimension.rst
  docs/source/generated/hotpdf.data.classes.HotCharacter.rst
  docs/source/generated/hotpdf.data.classes.Span.rst
  docs/source/generated/hotpdf.helpers.nanoid.rst
  docs/source/generated/hotpdf.hotpdf.HotPdf.rst
  docs/source/generated/hotpdf.memory_map.MemoryMap.rst
  docs/source/generated/hotpdf.processor.rst
  docs/source/generated/hotpdf.span_map.SpanMap.rst
  docs/source/generated/hotpdf.sparse_matrix.SparseMatrix.rst
  docs/source/generated/hotpdf.trie.Trie.rst
  docs/source/generated/hotpdf.trie.TrieNode.rst
  docs/source/generated/hotpdf.utils.rst
  pyproject.toml
Labels: CI/CD

#37 refactor: unified dev deps, update README.md
  .github/workflows/python-publish.yml
  .github/workflows/test.yml
  README.md
  pyproject.toml
Labels: documentation, CI/CD

#61 feat: tried to reduce memory but only cleaned up the code 😢
  .github/workflows/test.yml
  hotpdf/data/classes.py
  hotpdf/hotpdf.py
  hotpdf/span_map.py
  hotpdf/utils.py
  pyproject.toml
  tests/test_functions.py
Labels: enhancement

#62 feat: change return value of extract_spans
  .pre-commit-config.yaml
  hotpdf/data/classes.py
  hotpdf/helpers/nanoid.py
  hotpdf/hotpdf.py
  hotpdf/memory_map.py
  hotpdf/processor.py
  hotpdf/span_map.py
  hotpdf/sparse_matrix.py
  hotpdf/trie.py
  hotpdf/utils.py
  pyproject.toml
  tests/test_functions.py
  tests/test_load.py
Labels: enhancement
